### ISSUE TITLE
Include functionality to hide API key currently shown in googleCivic.js

### ISSUE THREAD

**Issue by rscottjohnson** [merinogeospatial/know-your-vote#27]
Include functionality to hide API key in `googleCivic.js`, which currently contains the API key in the `var queryURL =` statement.
  
### From the Project 2 guidelines:
`* Must not expose sensitive API key information on the server, see [Protecting-API-Keys-In-Node.md](../../../10-nodejs/03-Supplemental/Protecting-API-Keys-In-Node.md)`

**Comment by merinogeospatial** [comment]
Now done for both Google Civic and Propublica
